ci: Restrict NumPy for Python 3.10 mypy pre-commit hook
* Restrict numpy<2.5.0 for the Python 3.10 mypy pre-commit hook as NumPy v2.5.0
  uses the PEP 695 'type' statements which are Python 3.12+ and so cannot be
  be parsed by '--python-version=3.10'. This avoids

    error: Type statement is only supported in Python 3.12 and greater [syntax]

* Split the mypy pre-commit anchor by Python version so that Python 3.13 is not
  restricted by the cap on NumPy.