build: Update lower bound on iminuit to v2.7.0
* Update lower bound on iminuit to v2.7.0 as it is the 'oldest' SemVer release
that has the behavior:
> Minuit.hesse no longer sets the status of the FunctionMinimum unconditionally
> to valid if it was invalid before.

Without this fix, the situation can arise where `Minuit.hesse()` can cause
`Minuit.valid` to be True when it should be False.

            # Extra call to hesse() after migrad() is always needed for good error estimates. If you pass a user-provided gradient to MINUIT, convergence is faster.
            minimizer.hesse()
            hess_inv = minimizer.covariance
>           corr = hess_inv.correlation()
E           AttributeError: 'NoneType' object has no attribute 'correlation'