ci: Place upper bound on min supported setuptools
* Place an upper bound on setuptools of <70.0.0 for the 'minimum supported
  dependencies' workflow as setuptools v70.0.0 reduces pkg_resources
  useage.
   - Avoids a "cannot import name 'packaging' from 'pkg_resources'" ImportError
     caused by PyTorch.
   - c.f. https://setuptools.pypa.io/en/latest/pkg_resources.html